# Generated by Django 5.2 on 2025-11-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('rno', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], null=True)),
            ],
        ),
    ]
