# Generated by Django 5.2 on 2025-12-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bca', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('staff', 'staff'), ('principal', 'principal')], default='admin', null=True),
        ),
    ]
