# Generated by Django 5.2 on 2025-12-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('unique_id', models.CharField(blank=True, null=True)),
                ('field', models.CharField(blank=True, null=True)),
                ('role', models.CharField(blank=True, choices=[('doctor', 'doctor'), ('staff', 'staff'), ('nurse', 'nurse'), ('worker', 'worker')], max_length=10, null=True)),
            ],
        ),
    ]
